### ISSUE TITLE
Can't Install: 403 error

### ISSUE THREAD

**Issue by LiftedStarfish** [flathub/org.firestormviewer.FirestormViewer#20]
When I try to install it, it fails with the following error:
```
Error: While downloading https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-8-68380.tar.xz: Server returned status 403
error: Failed to install org.firestormviewer.FirestormViewer: While downloading https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-8-68380.tar.xz: Server returned status 403
```

**Comment by p1u3o** [comment]
@LiftedStarfish Can you try again?

**Comment by p1u3o** [comment]
No response and this will be solved by 

https://github.com/flathub/org.firestormviewer.FirestormViewer/pull/21

**Comment by p1u3o** [comment]
Reopened.

This is happening due to Cloudflare settings blocking the downloading of the viewer unless the browser is verified, killing installs of the Flatpak.

error: Failed to install org.firestormviewer.FirestormViewer: While downloading https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz: Server returned status 403

**Comment by caldanvers** [comment]
Any update as to when this will be resolved?

**Comment by HadetTheUndying** [comment]
> I'm having the same problem on multiple Distros. Maybe clone the file from the official website over to github and point the flatpak to that URL instead. This would take Cloudflare out of the equation and probably fix the issue. Just a suggestion.

We probably need to reach out to the Firestorm team about this because of redistribution of certain libraries. Ideally we could offer to host an FTP mirror for them. I could do this pretty simply, but I need the time and a point of contact with the Firestorm team that is actually willing to talk with one of us.

**Comment by Ashdemai** [comment]
Guys. The link "https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-8-68380.tar.xz:" has ":" at the end. Remove it and it will allow it to download the file. Can you remove it and let us try again? Also update your runtimes, they're at EOL.

**Comment by HadetTheUndying** [comment]
> Guys. The link "https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-8-68380.tar.xz:" has ":" at the end. Remove it and it will allow it to download the file. Can you remove it and let us try again? Also update your runtimes, they're at EOL.

We're using the older runtimes right now because of voice. If you think you can fix it please open a PR and we can review it.

**Comment by Ashdemai** [comment]
> We're using the older runtimes right now because of voice. 

I see.

> If you think you can fix it please open a PR and we can review it.

I'll try to look at the files. I'm not good the at this whole git thing, but I'll try.

**Comment by Ashdemai** [comment]
Turns out I'm dumb and it just copy pasted with the colon from the terminal, it's written fine. Confusing why it returns 403, if going straight through the link downloads it fine.

**Comment by HadetTheUndying** [comment]
> @HadetTheUndying is it possible to use this link instead of the one you have? https://downloads.firestormviewer.org/linux/Phoenix-Firestorm-Releasex64-6-6-14-69596.tar.xz
> 
> It's appears to be the same version, but this file name doesn't have OS in it.
> 
> I found this link being used in the firestorm-bin AUR if you're curious.

The problem is cloudflare's browser verification is stopping us from downloading. The links are still valid but it won't allow flatpak to download the file because it doesn't pass browser verification. There is no reason to use the non OpenSim release on Linux because LL and the Firestorm developers no longer bundle Havok. This is why we were talking about hosting a mirror

**Comment by paicen** [comment]
> @HadetTheUndying is it possible to use this link instead of the one you have? https://downloads.firestormviewer.org/linux/Phoenix-Firestorm-Releasex64-6-6-14-69596.tar.xz
> 
> It's appears to be the same version, but this file name doesn't have OS in it.
> 
> I found this link being used in the firestorm-bin AUR if you're curious.

Even using the aur there is a few other things you need to install to get voice working. It’s why most prefer to use the flatpak. 

Personally I gave up waiting for a solution and  installed everything I needed to get voice working and downloaded it straight from firestorm’s site.

**Comment by trawell** [comment]
Hello everyone,
Can we still expect a solution to this problem?
I have a single installation on the laptop that works.
Is it possible to copy this flatpak installation to another device?
If so, which are these under Linux Mint?

I like the flatpk version of Firestorm Viewer, would be really nice if you could get this working again.

Best regards
Trawell

**Comment by Xmetalfanx** [comment]
Hello, I am in Linux Mint chat rooms and someone just had an issue with a newer (Flatpak) version... took me a second but i noticed it's the same issue but different tar xz version .. the : at the end of the URL again

**Comment by HadetTheUndying** [comment]
> Hello, I am in Linux Mint chat rooms and someone just had an issue with a newer (Flatpak) version... took me a second but i noticed it's the same issue but different tar xz version .. the : at the end of the URL again 

Please read my above comments.

**Comment by paicen** [comment]
I’m so sick of hearing about cloudflare blocking blah blah blah. You know I every flatpak has zero problems downloading and installing. So maybe just maybe someone can take a hint. Just pure laziness

**Comment by MSM757** [comment]
> I’m so sick of hearing about cloudflare blocking blah blah blah. You know I every flatpak has zero problems downloading and installing. So maybe just maybe someone can take a hint. Just pure laziness

You clearly don't understand the depth of the issue. Firestorm Viewer while it is Open Source, the branding is under copyright. The copyright stamping is right on the website at the header of the main page. it's clear as day. That means if someone wanted to redistribute this, they totally could because it is open-source software, but they would be forced to use a different name and branding. That's why this "unofficial" flatpak points directly back to the official URL. Yes, it would be very easy to create a mirror, upload the .tar to that mirror and use that as the download source for the flatpak. You could set that up in less than five mins. But if you did that you could be sued over the trademark unless you have express written permission to do so by the original author which the maintainer of this flatpak has tried to obtain. Without written consent he would have to redistribute this under a new name. The artwork, name and branding would all have to change inside of the application itself as well as in the repo in order to be legal, and no sane person would do this because it would end up forking it into a whole new project that they would have to fully maintain themselves when the original intention was only to make a working Flatpak. So don't be mad at the maintainer of this flatpak. He's following the rules. Be mad at  "The Phoenix Firestorm Project Inc" for their bullshit copyright.  

I ran into a similar issue myself, i made a fork or a "respin" of Arch Linux a few years ago. I called it Arch_By_MM.  But because it had Arch in the name, the people from Arch Linux had something to say about it. They sent me a cease-and-desist letter via email. I had to take down my project and rename it. That project today is now known as StormOS. I no longer have anything to do with that project. All the work that went into StormOS was mostly done by Ben Fitzpatrick, Seeker, and a few others. I had nothing to do with StormOS itself but the original project files began as Arch_By_MM.  If the maintainer of this Flatpak did what you and others have suggested. He would find himself in a similar situation. 

So before you call the maintainer lazy, first understand what the issue actually is here.  Another prime example of a meaningless Copyright placed on top of a an open-source project, fucking things up for everyone downstream. 

That right there is the difference between something that's "Open Source" vs something that's "FREE/LIBRE". This is why FOSS advocates are so evangelical over it. It's because of shit like this.

**Comment by paicen** [comment]
> > I’m so sick of hearing about cloudflare blocking blah blah blah. You know I every flatpak has zero problems downloading and installing. So maybe just maybe someone can take a hint. Just pure laziness
> 
> You clearly don't understand the depth of the issue. Firestorm Viewer while it is Open Source, the branding is under copyright. The copyright stamping is right on the website at the header of the main page. it's clear as day. That means if someone wanted to redistribute this, they totally could because it is open-source software, but they would be forced to use a different name and branding. That's why this "unofficial" flatpak points directly back to the official URL. Yes, it would be very easy to create a mirror, upload the .tar to that mirror and use that as the download source for the flatpak. You could set that up in less than five mins. But if you did that you could be sued over the trademark unless you have express written permission to do so by the original author which the maintainer of this flatpak has tried to obtain. Without written consent he would have to redistribute this under a new name. The artwork, name and branding would all have to change inside of the application itself as well as in the repo in order to be legal, and no sane person would do this because it would end up forking it into a whole new project that they would have to fully maintain themselves when the original intention was only to make a working Flatpak. So don't be mad at the maintainer of this flatpak. He's following the rules. Be mad at "The Phoenix Firestorm Project Inc" for their bullshit copyright.
> 
> I ran into a similar issue myself, i made a fork or a "respin" of Arch Linux a few years ago. I called it Arch_By_MM. But because it had Arch in the name, the people from Arch Linux had something to say about it. They sent me a cease-and-desist letter via email. I had to take down my project and rename it. That project today is now known as StormOS. I no longer have anything to do with that project. All the work that went into StormOS was mostly done by Ben Fitzpatrick, Seeker, and a few others. I had nothing to do with StormOS itself but the original project files began as Arch_By_MM. If the maintainer of this Flatpak did what you and others have suggested. He would find himself in a similar situation.
> 
> So before you call the maintainer lazy, first understand what the issue actually is here. Another prime example of a meaningless Copyright placed on top of a an open-source project, fucking things up for everyone downstream.
> 
> That right there is the difference between something that's "Open Source" vs something that's "FREE/LIBRE". This is why FOSS advocates are so evangelical over it. It's because of shit like this.

I have been using Linux since 1998, I am quite aware of how it works. And I stand by the lazy statement. 

I’m not interested in anyone else maintaining it. My lazy comment is directed at those already maintaining it. 

Now if you want to talk about someone else maintaining it we can talk about that. Do you have a desire to be that person? I’m happy to help you get ahold of the people at phoenix, it’s not that complicated. I’ve spoken to them twice in the past. 

I’m just tired of hearing about cloudflare. I’m keeping an eye on this thread purely for curiosity sake. Most people (that I’ve talked to at least) like the flatpak because voice works out of the box. I used it for that same reason. 

Over the last year I’ve gotten more people interested in SL, because i use it as a tool for real world causes and find it to be a great tool for bridging the gap between real world and fantasy. It helps people connect in a way that is useful. 

But over the last month I’ve had to help 16 people get voice working with the direct download version because the flat has been unavailable. Getting voice to work isn’t hard, providing the distro they use has everything that’s needed  available through their repo. If so it takes about 3-5 minutes on average) 

The experience however has reminded me why I’ve never been a huge fan of flatpak or snaps for that matter. Everyone wants a prepackaged solution instead of just taking the time to learn how things work. 

And that’s fine I get it. Again I’m just tired of hearing about cloudfare and not hearing any solutions.

**Comment by Xmetalfanx** [comment]
have to admit i didn't expect some of this. (posts since mine)  Was just helping someone in chat and I saw someone opened an issue that was similar.

**Comment by HadetTheUndying** [comment]
> I'm so sick of hearing about Cloudflare blocking blah blah blah. You know, every flatpak has zero problems downloading and installing. So maybe just maybe someone can take a hint. Just pure laziness.

 Feel free to try and fix it yourself? We do this in our spare time, most of us have day jobs. We are not affiliated with the Firestorm team. You could try showing them this issue. We didn't cause it, it worked fine until they switched to Cloudflare CDN. This kind of reaction is unacceptable. This is a public repo, if it's so easy to fix, open a PR. Otherwise trust that we're trying to resolve the issue when we have time to test things like a source build which would be missing things like FMOD.

**Comment by paicen** [comment]
> have to admit i didn't expect some of this. (posts since mine) Was just helping someone in chat and I saw someone opened an issue that was similar.

I honestly hadn’t expected this to go on this long. This happened a few months ago too but only lasted a day or two (that i noticed). I’ve just been watching it kind of close because I’ve had to help so many people get voice to work after they tried the flat and it failed. So I’m just watching more than anything. I let myself get carried away on occasion lol. I just can’t direct people that I bring into SL to the flat until the whole thing works itself out.

**Comment by Xmetalfanx** [comment]
i dont even use the app but the feel the need to thank the people associated with repo for the work they have done.   This will probably be my last post here as to not get a git issue off topic 

Thanks guys

**Comment by HadetTheUndying** [comment]
I have opened a JIRA ticket in hopes of finding some sort of solution for this. In the mean time Alchemy Viewer does offer an AppImage and I told them I would help them with a flatpak at one point. This might be an acceptable compromise for some users currently. Hopefully we get some sort of response from the Firestorm team. Best case scenario they allow me to host a mirror. Worst case scenario we'll fight with the build system until we get something that works. This is a very busy time of year for me, today was my day off. I will not be able to actively track this issue for awhile. I will keep an eye out for responses in the other ticket I opened.

https://jira.firestormviewer.org/browse/FIRE-33379

**Comment by yaynstuff** [comment]
Have you checked lately to see if this is still an issue?

**Comment by paicen** [comment]
> Have you checked lately to see if this is still an issue?

It’s still an issue. I just checked after your post.

**Comment by yaynstuff** [comment]
Whats the link you are trying?

**Comment by HadetTheUndying** [comment]
> Whats the link you are trying?

https://downloads.firestormviewer.org/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz This is the link we were pointed at in the latest release. If the link has changed I can try updating it. Packaging locally appears to work for me now.

**Comment by HadetTheUndying** [comment]
Oh my god I see the problem

I am so sorry.

**Comment by paicen** [comment]
> I have opened a JIRA ticket in hopes of finding some sort of solution for this. In the mean time Alchemy Viewer does offer an AppImage and I told them I would help them with a flatpak at one point. This might be an acceptable compromise for some users currently. Hopefully we get some sort of response from the Firestorm team. Best case scenario they allow me to host a mirror. Worst case scenario we'll fight with the build system until we get something that works. This is a very busy time of year for me, today was my day off. I will not be able to actively track this issue for awhile. I will keep an eye out for responses in the other ticket I opened.
> 
> https://jira.firestormviewer.org/browse/FIRE-33379

I thought they had an appimage  but I haven’t been able to find it

**Comment by yaynstuff** [comment]
https://downloads.firestormviewer.org/release/linux/Phoenix-FirestormOS-Releasex64-6-6-14-69596.tar.xz

You have the wrong URL. Try that

**Comment by HadetTheUndying** [comment]
When this build Finishes it should work. Please test it to anyone that was having trouble before. I apologize for not noticing this, I just assumed that it was a persistent issue, that's on me. Once it's verified working I'll ask @p1u3o to merge it.

https://github.com/flathub/org.firestormviewer.FirestormViewer/pull/25

**Comment by p1u3o** [comment]
Cloudflare is no longer blocking these URLs.
